name: flutterwhatsapp
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  camera: ^0.5.8+5
  cloud_firestore: ^2.5.3
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  firebase_storage: ^10.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_local_notifications: ^9.0.0
  fluttertoast: ^8.0.8
  hooks_riverpod: ^0.14.0+5
  image_picker: ^0.8.3+2
  uuid: ^3.0.4
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  photo_view: ^0.13.0
  file_picker: ^4.3.0
  open_file: ^3.2.1
  shared_preferences: ^2.0.9

  # flutter_document_picker: ^4.0.1

dev_dependencies:
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: fonts/kklearning.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - fonts/kklearning.png
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: YellowTail
      fonts:
        - asset: fonts/YellowTail/Yellowtail-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
